remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "Zafira Solidaire's landing page"
description: "A landing page to give an overwiew of our portfolio project: ZafiraSolidaire's website."
